const $=id=>document.getElementById(id),token=location.hash.slice(1);history.replaceState(null,'',location.pathname);
let state=null,busy=false;
const disable=()=>{for(const id of ['primary','finish','sound'])$(id).disabled=true;document.querySelectorAll('#exercises button').forEach(b=>b.disabled=true);};
async function api(path,body={}){const r=await fetch('/remote/'+path,{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({token,...body}),signal:AbortSignal.timeout(3000)});const d=await r.json();if(!r.ok)throw Error(d.error);return d;}
function render(){disable();if(!state?.connected)return;const p=state.phase;const labels={ready:'Start',countdown:'Cancel countdown',running:'Pause',paused:'Resume',guide:'Ready to exercise'};$('exercise').textContent=state.title;$('status').textContent={waiting:'Choose an exercise on the computer.',ready:'Ready when you are.',countdown:'Get ready. Watch the computer countdown.',running:'Exercise recording.',paused:'Paused. Resume when ready.',finished:'Exercise finished.',guide:'Watch the demonstration on the laptop, then continue.'}[p];$('primary').textContent=labels[p]||'Start';$('primary').disabled=busy||!labels[p];$('finish').disabled=busy||!['running','paused'].includes(p);$('sound').disabled=busy||p==='finished';renderExercises();$('sound').textContent=state.voice?'Voice on · tap to mute':'Voice off · tap to enable';}
async function command(action,exercise=''){if(busy||!state?.connected)return;busy=true;render();try{await api('command',{action,exercise,id:Date.now()+'-'+Math.random().toString(36).slice(2)});$('status').textContent='Sent to computer…';}catch(e){$('status').textContent=e.message;}finally{setTimeout(()=>{busy=false;},1000);}}
$('primary').onclick=()=>command({ready:'start',countdown:'cancel',running:'pause',paused:'resume',guide:'continue'}[state?.phase]);$('finish').onclick=()=>command('finish');$('sound').onclick=()=>command('voice');
async function poll(){if(!token)return;try{state=await api('state');if(state.connected)render();else{disable();$('status').textContent='Computer disconnected. Reconnect before continuing.';}}catch{disable();state=null;$('status').textContent='Connection unavailable or pairing ended. Scan a new code on the computer.';}setTimeout(poll,700);}
poll();

let listKey='';
function renderExercises(){const list=state.exercises||[],key=JSON.stringify(list);if(key!==listKey){listKey=key;$('exercises').replaceChildren();for(const ex of list){const b=document.createElement('button');b.textContent=ex.title;b.onclick=()=>command('select',ex.id);$('exercises').append(b);}}document.querySelectorAll('#exercises button').forEach(b=>b.disabled=busy||!['waiting','ready','finished'].includes(state.phase));}
