import {exerciseContextFacts} from './exercise-context.mjs?v=pubmed-1';
import {renderExerciseEvidenceGuide} from './exercise-evidence.mjs?v=cards-1';
import {EXERCISE_NAMES,METRICS,finite,seriesFor,dailyRows,metricSummary,formatValue,localDate,dayNumber,dayAt,postOpDay} from './progress-data.mjs?v=pubmed-1';
import {esc,tile,dayLabel,shortDate,chart,csvDownload,download} from './progress-shared.mjs';
import {RECOVERY_SOURCES,REFERENCES} from './recovery-references.mjs';
import {readProms,scopedProms,promOverview,PROM_NAMES} from './patient-measures.mjs';
const link=k=>`<a href="${RECOVERY_SOURCES[k].url}" target="_blank" rel="noopener">${esc(RECOVERY_SOURCES[k].name)}</a>`;
const observationNote='Observed video values are approximate 2D measurements. A best recorded value is not a diagnosis, a validated technique score or a personal recovery target.';
const outcomeLabel=metric=>metric.best==='min'?'Lowest recorded':metric.best==='max'?'Highest recorded':metric.best==='target'?'Closest to entered target':'Observed range';
export function renderProgressToDate(host,records,options={}) {
 const {patientId,operationDate}=options,today=localDate(),scope=JSON.stringify([patientId,operationDate]);
 const previous=host.dataset.scope===scope?Object.fromEntries([...host.querySelectorAll('[data-choice]')].map(e=>[e.dataset.choice,e.value])):{};host.dataset.scope=scope;
 let proms=[],promError='';try{proms=scopedProms(readProms(options.storage||localStorage),patientId,operationDate);}catch(e){promError=e.message;}
 const measuredReports=records.filter(r=>r.exercise_analysis),days=new Set(records.map(r=>r.started_at.slice(0,10))),day=postOpDay(today,operationDate);
 const overview=Object.keys(EXERCISE_NAMES).map(exercise=>{
  const a=records.filter(r=>r.exercise===exercise&&r.exercise_analysis?.exercise===exercise).at(-1),keys={straight_leg_raise:['extraBend','hip','lift','hold','return'],seated_extension:['leastBend','straightening','cycle','return'],heel_slide:['greatestBend','returnBend','slideRange','consistency']}[exercise],metrics=keys.map(key=>METRICS[exercise].find(m=>m.id===key));
  return `<section class="pt-panel pt-exercise-card"><h2>${esc(EXERCISE_NAMES[exercise])}</h2><p class="pt-muted">${a?`${esc(shortDate(a.started_at.slice(0,10)))} · ${esc(dayLabel(postOpDay(a.started_at.slice(0,10),operationDate)))} · ${esc(a.exercise_analysis.config?.side||'Unknown')} leg`:'No saved video analysis yet'}</p><dl>${metrics.map(metric=>`<div><dt>${esc(metric.label)}</dt><dd>${esc(formatValue(a?finite(metric.get(a)):null,metric.unit))}</dd></div>`).join('')}</dl></section>`;
 }).join('');
 host.innerHTML=`<div class="pt-heading"><div class="eyebrow">Your exercise performance</div><h1>Exercise metrics</h1><p>Results from your exercise recordings, one day at a time. Dedicated bending and straightening checks appear in your <a href="?view=recovery-summary">Recovery summary</a>.</p><p class="pt-context">Patient ${esc(patientId)} · ${operationDate?`Operation ${esc(shortDate(operationDate))} · ${esc(dayLabel(day))} today`:'Set your operation date to see days after surgery'} · <a href="?view=patient-details#patient">Change patient details</a></p></div>
 <div class="pt-notice"><strong>Typical recovery ranges, not mandatory deadlines.</strong><p>People recover at different rates. Your physiotherapist’s plan, starting range, pain, swelling and everyday function matter alongside these numbers. The literature describes groups of patients; it does not set a pass or fail result for your day of recovery.</p></div>
 <div class="pt-tiles">${tile('Exercise days recorded',days.size,`${records.length} saved sessions for these patient details`)}${tile('Saved video reports',measuredReports.length,'Only recorded measurements appear below')}${tile('Questionnaire results',proms.length,'KOOS JR and Oxford Knee Score recorded separately')}</div>
 <div class="pt-three">${overview}</div>
 ${renderExerciseEvidenceGuide()}
 <section class="pt-panel" aria-label="Day by day exercise measurements"><h2>Explore an exercise</h2><p>Choose an exercise and a measurement to see your daily results and what the result can tell you.</p><div class="pt-controls"><label>Exercise<select data-choice="exercise">${Object.entries(EXERCISE_NAMES).map(([id,name])=>`<option value="${id}">${name}</option>`).join('')}</select></label><label>Measurement<select data-choice="metric"></select></label><label>Recording series<select data-choice="series"></select></label></div><div class="pt-controls pt-date-controls"><label>From date<input data-choice="from" type="date"></label><label>To date<input data-choice="to" type="date"></label><button type="button" data-recent>Last 30 days</button><button type="button" data-all>Latest year of recordings</button></div><p data-series-note class="pt-muted"></p><div data-daily-results aria-live="polite"></div></section>
 <section class="pt-panel"><h2>Patient-reported recovery</h2><p>Your symptoms and function add information that an exercise video cannot provide.</p><div class="pt-tiles">${promOverview(proms).map(p=>tile(`${PROM_NAMES[p.instrument]} · ${p.side} knee`,`${p.latest.score} / ${p.instrument==='koos_jr'?100:48}`,`${shortDate(p.latest.date)} · ${dayLabel(postOpDay(p.latest.date,operationDate))}`)).join('')||'<p>No questionnaire results saved yet.</p>'}</div>${promError?`<p role="status">${esc(promError)}</p>`:''}<a class="pt-link-button" href="?view=patient-measures#patientMeasures">Open Patient-reported measures →</a></section>
 <section class="pt-panel"><div class="eyebrow">Research context</div><h2>What typical recovery can look like</h2><p><a href="?view=recovery-timeline">Explore the chronological recovery timeline →</a></p><div class="pt-tiles pt-reference-tiles">${tile('Early after surgery','70 to 90°','Active knee flexion, middle 50%')}${tile('Around 1 month','95 to 115°','Active knee flexion, middle 50%')}${tile('Around 3 months','109 to 122°','Active knee flexion, middle 50%')}</div><p>These are the middle 50% of active knee flexion observations in the reference chart, not the full range of recovery. ${link('chart')}. A heel-slide video is not interchangeable with a clinical range measurement. We do not interpolate an expected angle for every day or assign a patient percentile.</p><div class="pt-reference-list">${REFERENCES.map(r=>`<details><summary><span>${esc(r.measure)}</span><small>${esc(r.when)}</small></summary><p><strong>Published context.</strong> ${esc(r.reference)}</p><p>${esc(r.meaning)}</p><p><strong>What this app can show.</strong> ${esc(r.available)}</p><p>${link(r.source)}</p></details>`).join('')}</div><p class="pt-muted">Sources reviewed 13 September 2026. ${link('guideline')}. No universal daily numerical reference is supplied where the cited evidence does not support one.</p></section>
 <section class="pt-panel"><h2>Your summary to keep or share</h2><p>${observationNote} Records are stored in this browser on this device.</p><div class="pt-actions"><button type="button" data-summary>Download progress summary</button><button type="button" data-metrics>Download all recorded exercise metrics (CSV)</button></div></section>`;
 const select=n=>host.querySelector(`[data-choice="${n}"]`),exercise=select('exercise'),metricSelect=select('metric'),seriesSelect=select('series'),from=select('from'),to=select('to');
 exercise.value=EXERCISE_NAMES[previous.exercise]?previous.exercise:records.filter(r=>EXERCISE_NAMES[r.exercise]).at(-1)?.exercise||'straight_leg_raise';
 to.value=previous.to||today;from.value=previous.from||dayAt(Math.max(dayNumber(today)-89,operationDate&&dayNumber(operationDate)!==null&&operationDate<=today?dayNumber(operationDate):dayNumber(today)-89));
 let groups=[],metric;
 function metrics(){metricSelect.innerHTML=METRICS[exercise.value].map(m=>`<option value="${m.id}">${esc(m.label)}</option>`).join('');if(METRICS[exercise.value].some(m=>m.id===previous.metric))metricSelect.value=previous.metric;series();}
 function series(){
  metric=METRICS[exercise.value].find(m=>m.id===metricSelect.value);groups=seriesFor(records,exercise.value,metric);
  seriesSelect.innerHTML=groups.map((g,i)=>`<option value="${i}">${esc(g.label)} · ${esc(shortDate(g.records[0].started_at.slice(0,10)))}${groups.filter(x=>x.label===g.label).length>1?` · series ${i+1}`:''}</option>`).join('')||'<option value="">No saved series</option>';
  seriesSelect.value=String(groups.length-1);draw();
 }
 function draw(){
  const group=groups[Number(seriesSelect.value)],chosen=group?.records||[],selected=chosen.filter(r=>r.started_at.slice(0,10)>=from.value&&r.started_at.slice(0,10)<=to.value),panel=host.querySelector('[data-daily-results]');
  let rows;try{rows=dailyRows(chosen,metric,from.value,to.value,operationDate);}catch(e){panel.innerHTML=`<p role="alert">${esc(e.message)}</p>`;return;}
  const stats=metricSummary(selected,metric),fmt=v=>formatValue(v,metric.unit),best=stats.best?fmt(stats.best.value):stats.min!==null?`${fmt(stats.min)} to ${fmt(stats.max)}`:'Not recorded';
  const c=chosen.at(-1)?.exercise_analysis?.config;
  host.querySelector('[data-series-note]').textContent=group?`${group.label}. Each series keeps the same recorded method, leg, analysis settings, assistance and added resistance. ${metric.source==='video'?`Visibility threshold: ${finite(c?.minVisibility)!==null?Math.round(c.minVisibility*100)+'%':'not recorded'}. `:''}Use the same assistance and camera setup when comparing sessions; these are not automatically verified.`:'Finish and analyse an exercise to start a video series. Patient ratings and older live measurements have their own dropdown entries.';
  let prior=null;
  panel.innerHTML=`<div class="pt-tiles">${tile('Latest measured in date range',stats.latest?fmt(stats.latest.value):'Not recorded',stats.latest?shortDate(stats.latest.record.started_at.slice(0,10)):'No usable measurement for this selection')}${tile(stats.best?outcomeLabel(metric):'Observed range',best,stats.best?`${shortDate(stats.best.record.started_at.slice(0,10))}${stats.target>0?` · entered target ${fmt(stats.target)}`:''}`:'No universal best value assigned')}${tile('Change from first measured',stats.change===null?'Not available':`${stats.change>0?'+':''}${fmt(stats.change)}`,`${rows.filter(r=>r.value!==null).length} measured days in the selected period`)}</div><div class="pt-interpretation"><h3>What is a good outcome?</h3><p>${esc(metric.interpretation)}</p><small>${esc(observationNote)}</small></div>${chart(rows,metric.unit,metric.label)}<p class="pt-muted">Each dot shows the latest measurable session on that day in this series. Gaps are unmeasured. The best recorded card considers all measured sessions in the chosen date range. Changes are descriptive, not proof of clinically important improvement.</p><div class="pt-actions"><button type="button" data-daily-export>Download this daily view (CSV)</button><label class="pt-check"><input type="checkbox" data-recorded-only>Show recorded days only</label></div><div class="pt-table-wrap"><table><caption>${esc(metric.label)} · daily results</caption><thead><tr><th scope="col">Date</th><th scope="col">After surgery</th><th scope="col">Latest measurement</th><th scope="col">Change from previous measured day</th><th scope="col">Sessions</th></tr></thead><tbody>${rows.slice().map(row=>{
   const change=row.value!==null&&prior!==null?row.value-prior:null;if(row.value!==null)prior=row.value;
   return `<tr data-has-session="${row.sessions.length>0}"><th scope="row">${esc(shortDate(row.date))}</th><td>${esc(dayLabel(row.day))}</td><td>${esc(fmt(row.value))}</td><td>${change===null?'Not available':`${change>0?'+':''}${esc(fmt(change))}`}</td><td>${row.sessions.length?`<details><summary>${row.measured} measured / ${row.sessions.length} saved</summary>${row.sessions.map(r=>`<p>${esc(r.started_at.slice(11,16))}: ${esc(fmt(finite(metric.get(r))))} ${options.onReview?`<button type="button" data-session="${records.indexOf(r)}">Full report</button>`:''}</p>`).join('')}</details>`:'No session saved'}</td></tr>`;
  }).reverse().join('')}</tbody></table></div>`;
  panel.querySelector('[data-recorded-only]').onchange=e=>panel.querySelectorAll('tbody tr').forEach(row=>row.hidden=e.target.checked&&row.dataset.hasSession!=='true');
  panel.querySelectorAll('[data-session]').forEach(b=>b.onclick=()=>options.onReview(records[Number(b.dataset.session)],records));
  panel.querySelector('[data-daily-export]').onclick=()=>csvDownload('exercise-daily-progress.csv',[['Patient','Operation date','Date','Day after surgery','Exercise','Metric','Unit','Latest measurable value','Measured sessions','Saved sessions','Recording series'],...rows.map(r=>[patientId,operationDate,r.date,r.day,EXERCISE_NAMES[exercise.value],metric.label,metric.unit,r.value,r.measured,r.sessions.length,group?.key||''])]);
 }
 exercise.onchange=metrics;metricSelect.onchange=series;seriesSelect.onchange=draw;from.onchange=draw;to.onchange=draw;
 host.querySelector('[data-recent]').onclick=()=>{to.value=today;from.value=dayAt(dayNumber(today)-29);draw();};
 host.querySelector('[data-all]').onclick=()=>{const dates=records.filter(r=>r.exercise===exercise.value).map(r=>r.started_at.slice(0,10)).filter(d=>dayNumber(d)!==null).sort();to.value=dates.at(-1)||today;from.value=dates.length?dayAt(Math.max(dayNumber(dates[0]),dayNumber(to.value)-365)):dayAt(dayNumber(today)-89);draw();};
 host.querySelector('[data-summary]').onclick=()=>{
  const text=['Kneora: PROGRESS TO DATE',`Patient: ${patientId}`,`Operation: ${operationDate||'not set'}`,`Generated: ${today} (${dayLabel(day)})`,`${records.length} sessions, ${days.size} exercise days, ${measuredReports.length} video reports.`,observationNote,'Typical recovery ranges are not mandatory deadlines.'];
  for(const [id,name] of Object.entries(EXERCISE_NAMES)){
   text.push('',name.toUpperCase());
   for(const metric of METRICS[id])for(const group of seriesFor(records,id,metric)){
    const stats=metricSummary(group.records,metric);if(!stats.latest)continue;
    text.push(`${metric.label} (${group.label}): latest ${formatValue(stats.latest.value,metric.unit)} on ${stats.latest.record.started_at.slice(0,10)}. ${stats.best?`${outcomeLabel(metric)}: ${formatValue(stats.best.value,metric.unit)} on ${stats.best.record.started_at.slice(0,10)}.`:'No universal best value assigned.'}`,`Interpretation: ${metric.interpretation}`);
   }
  }
  text.push('','EXERCISE CONTEXT');for(const r of records)text.push(`${r.started_at} | ${EXERCISE_NAMES[r.exercise]||r.exercise}: ${exerciseContextFacts(r).map(([label,value])=>`${label}: ${value}`).join('; ')}`);
  text.push('','PATIENT-REPORTED MEASURES');for(const p of promOverview(proms))text.push(`${PROM_NAMES[p.instrument]}, ${p.side}: ${p.latest.score} / ${p.instrument==='koos_jr'?100:48} on ${p.latest.date}.`);
  if(!proms.length)text.push('No questionnaire scores recorded.');
  text.push('','PUBLISHED RECOVERY CONTEXT');for(const r of REFERENCES)text.push(`${r.measure} | ${r.when}: ${r.reference} ${r.meaning}`,RECOVERY_SOURCES[r.source].url);
  download('kneora-progress-summary.txt',text.join('\n'));
 };
 host.querySelector('[data-metrics]').onclick=()=>csvDownload('all-exercise-metrics.csv',[['Patient','Operation date','Session date and time','Day after surgery','Exercise','Metric','Value','Unit','Source','Recording series','Assistance','Resistance'],...records.flatMap(r=>(METRICS[r.exercise]||[]).map(metric=>[patientId,operationDate,r.started_at,postOpDay(r.started_at.slice(0,10),operationDate),EXERCISE_NAMES[r.exercise],metric.label,finite(metric.get(r)),metric.unit,metric.source,seriesFor([r],r.exercise,metric)[0]?.key||'',exerciseContextFacts(r)[0][1],exerciseContextFacts(r)[1][1]]))]);
 metrics();
}
