import {esc,shortDate,dayLabel,csvDownload,download} from './progress-shared.mjs';
import {localDate,postOpDay,dayNumber,dayAt,finite,METRICS} from './progress-data.mjs';
import {readProms,scopedProms,PROM_NAMES} from './patient-measures.mjs';
import {readMeasurements,scopedMeasurements,saveMeasurementSet,measurementSeriesKey,depthImport,SOURCE_NAMES,MOTION_NAMES,MODE_NAMES,POSITION_NAMES} from './recovery-measurements.mjs?v=endpoint-3-flexible';
import {createEndpointCamera} from './recovery-camera.mjs?v=flexible-pair-1';
import {maximumMovementTrend,combinedMovementChart} from './recovery-trends.mjs?v=large-graph-1';
import {AppVoice} from './app-voice.mjs';
import {EndpointCountdown} from './endpoint-countdown.mjs?v=2';
import {RECOVERY_SOURCES} from './recovery-references.mjs';

const degrees=n=>finite(n)===null?'Not measured':`${Math.round(n)}°`;
const note=r=>`${SOURCE_NAMES[r.source.kind]} · ${MODE_NAMES[r.mode]} · ${POSITION_NAMES[r.position]}`;
const metricValue=(r,id)=>finite(METRICS[r?.exercise]?.find(m=>m.id===id)?.get(r));
const src=(key,label)=>`<a href="${RECOVERY_SOURCES[key].url}" target="_blank" rel="noopener">${label}</a>`;
export function recoveryExerciseContext(records,{patientId,operationDate,side,asOf=localDate()}){
 const scoped=records.filter(r=>r.patient_id===patientId&&(r.operation_date||'')===(operationDate||'')&&dayNumber(r.started_at?.slice(0,10))!==null&&r.started_at.slice(0,10)<=asOf&&
  (r.exercise_analysis?.config?.side||r.measurement?.side)===side).sort((a,b)=>a.started_at.localeCompare(b.started_at));
 const recent=scoped.filter(r=>r.started_at.slice(0,10)>=dayAt(dayNumber(asOf)-6)),slr=scoped.filter(r=>r.exercise==='straight_leg_raise'&&metricValue(r,'extraBend')!==null).at(-1);
 const symptoms=scoped.filter(r=>finite(r.patient?.pain_0_10)!==null).at(-1);
 return {recent,days:new Set(recent.map(r=>r.started_at.slice(0,10))).size,slr,extraBend:slr?metricValue(slr,'extraBend'):null,symptoms};
}

export function renderRecoverySummary(host,exerciseRecords,options={}){
 host._destroy?.();
 const {patientId='',operationDate='',side:initialSide=''}=options,storage=options.storage||localStorage;
 const operatedSide=['left','right'].includes(initialSide)?initialSide:null;
 const today=localDate();let rows=[],proms=[],storageError='',draft=null,captureGroup='',cameraReady=false,capturing=false,counting=false,completed=[],liveAttempt=false,alive=true;
 try{rows=readMeasurements(storage);}catch(e){storageError=e.message;}
 try{proms=scopedProms(readProms(storage),patientId,operationDate);}catch(e){storageError+=[storageError?' ':'',e.message].join('');}
 host.innerHTML=`<header class="rs-heading"><div class="eyebrow">Your recovery · beyond exercise counts</div><h1>Recovery summary</h1><p>Your best recorded knee bending and straightening, measured from the day of surgery.</p><p class="pt-context">Patient ${esc(patientId)} · ${operationDate?`Operation ${esc(shortDate(operationDate))}`:'Operation date not set'} · <a href="?view=settings#patient">Change patient details</a></p></header>
 <div class="rs-summary-controls"><label>Knee in summary<select data-summary-side><option value="left">Left knee</option><option value="right">Right knee</option></select></label><label>Summary date<input data-summary-date type="date" value="${today}" max="${today}"></label><span data-summary-day></span></div>
 <p class="rs-storage-error" role="status">${esc(storageError)}</p><div class="rs-primary-trends" data-recovery-graphs></div>
 <section class="rs-panel rs-measure" id="recoveryCheck"><div class="eyebrow">A separate recovery check</div><h2>Take a measurement</h2><p>Use the position and assistance agreed with your physiotherapist. Move to your comfortable limit and tell the app when you are there. There is no required pause at the start.</p>
 <form data-endpoint-form><label class="rs-plan">Measurement plan<select data-measurement-plan><option value="both">Bending, then straightening</option><option value="single">One movement only</option></select></label><p data-sequence-status class="rs-sequence-status" role="status">First measure bending. Rest, then measure straightening when you are ready.</p><div class="rs-fields"><label>Movement<select name="motion"><option value="bend">Knee bending</option><option value="straighten">Knee straightening</option></select></label><label>Knee being measured<select name="side"><option value="left">Left knee</option><option value="right">Right knee</option></select></label><label>Assistance<select name="mode"><option value="active">Without assistance</option><option value="assisted">With assistance</option><option value="passive">Clinician-assessed passive range</option></select></label><label>Position<select name="position"><option value="supine">Lying on your back</option><option value="seated">Seated</option></select></label><label>Measurement date<input name="date" type="date" required value="${today}" max="${today}"></label></div>
 <p class="rs-date-note">Camera measurements are dated automatically on the day of capture. For uploaded photos or a clinical result, use the original assessment date.</p>
 <div class="rs-camera-guide"><span class="rs-step">1</span><p>Place the camera side-on, with the hip, knee and ankle visible. Keep the same setup for later comparisons.</p><span class="rs-step">2</span><p>Once you are positioned, show an open palm towards the camera for two seconds, or ask a helper to press the red Capture this position button. Use Marin’s countdown to settle at your comfortable limit. You do not need to hold the end position throughout the countdown. During capture, stay as still as comfortable while the app takes up to 10 pictures over six seconds. Small movements are fine. You can relax or finish early if needed.</p><span class="rs-step">3</span><p>When capture finishes, relax your leg, review the result and save it. Lower or close your hand before showing your palm for another measurement. These camera estimates have not been clinically validated.</p></div>
 <div class="rs-camera-wrap" hidden><video data-endpoint-video muted playsinline hidden></video><canvas data-endpoint-canvas aria-label="Camera view with the measured leg highlighted"></canvas><div class="rs-countdown" data-countdown hidden aria-live="polite"></div><div class="rs-live-angle"><strong data-live-angle>Not measured</strong><span>Approximate knee bend · 0° means straight</span><small>Live display averaged across up to five recent frames.</small></div><div class="rs-gesture-guide" data-gesture-guide hidden><strong data-gesture-label></strong><progress data-gesture-progress max="1" value="0" aria-label="Open-palm hold progress"></progress></div></div><div class="rs-camera-actions"><button type="button" class="pt-primary" data-open-camera>Open camera</button><button type="button" class="rs-capture-button" data-capture disabled>Capture this position</button><button type="button" data-stop-camera disabled>Stop camera</button></div><p data-camera-status role="status">Open the camera, get into position, then show your open palm or ask a helper to press the red capture button. No microphone is used.</p>
 <p data-voice-status class="rs-voice-status">Marin (AI voice) provides the countdown and guidance. Written instructions remain available.</p><details class="rs-alternative"><summary>Assisted measurement: use photographs</summary><p>Ask a helper to take 3 to 10 photographs of your operated knee during the same comfortable end-position attempt, keeping the camera side-on with the hip, knee and ankle visible. Select the date they were taken. The app measures each photograph independently and averages the usable angles. Use one consistent side-on view for each set. This measurement does not combine different viewpoints into a 3D angle.</p><label class="pt-check"><input type="checkbox" data-photo-view><span>These photos show the same knee, end-position attempt and side-on camera view.</span></label><label class="rs-upload">End-position photos<input data-endpoint-images type="file" accept="image/*" multiple></label></details>
 <details class="rs-alternative"><summary>Add a 3D camera or clinical measurement</summary><p><strong>3D camera: not connected.</strong> A compatible device export can be imported below. Direct capture will need the camera model and its software connection.</p><label class="rs-upload">Import depth-camera joint coordinates (JSON)<input data-depth-file type="file" accept=".json,application/json"></label><p>The importer calculates the bend from depth-derived hip, knee and ankle coordinates. MediaPipe’s predicted 3D landmarks are not a second camera measurement.</p><div class="rs-fields"><label>Clinical angle, degrees of bend<input name="clinical_angle" type="number" min="0" max="180" step="0.1" placeholder="0 means straight"></label><label>Clinical instrument or method<input name="clinical_device" maxlength="160" placeholder="For example, goniometer"></label></div><button type="button" data-use-clinical>Use this clinical result</button><p>Enter a result already measured by a clinician. This unsigned angle format cannot record hyperextension or calculate clinical extension lag.</p></details>
 <section data-measurement-preview class="rs-preview" aria-live="polite" hidden></section><label class="pt-check"><input name="confirmed" type="checkbox"><span>The patient reported reaching their comfortable limit for this measurement.</span></label><label class="rs-note">Note, including any assistance or symptoms<textarea name="note" rows="2" maxlength="1000"></textarea></label><button type="submit" class="pt-primary" data-save-measurement disabled>Save recovery measurement</button><p data-save-status role="status"></p></form></section>
 <details class="rs-panel rs-other-results"><summary>Exercise participation and other results</summary><div data-recovery-cards></div></details>
 <footer class="rs-footer"><p>Typical recovery involves movement, symptoms, strength and everyday function. These do not all improve at the same rate. ${src('function','Mizner et al.')}</p><div class="pt-actions"><a class="pt-link-button" href="?view=recovery-timeline">Expected recovery timeline →</a><a class="pt-link-button" href="?view=progress-to-date">Exercise metrics →</a><button type="button" data-summary-download>Download patient summary</button><button type="button" data-export-measurements>Download measurements (CSV)</button></div></footer>`;
 const q=s=>host.querySelector(s),form=q('[data-endpoint-form]'),field=n=>form.elements.namedItem(n),summarySide=q('[data-summary-side]'),summaryDate=q('[data-summary-date]');
 summarySide.value=operatedSide||'left';
 field('side').innerHTML=operatedSide?`<option value="${operatedSide}">${operatedSide==='left'?'Left':'Right'} knee · operated knee</option>`:'<option value="">Set your operated leg in Settings</option>';
 field('side').disabled=true;
 field('side').parentElement.insertAdjacentHTML('beforeend','<small>Set automatically from <a href="?view=settings#side">your operated leg in Settings</a>.</small>');
 if(!operatedSide)q('[data-camera-status]').textContent='Select your operated leg in Settings before taking a recovery measurement.';
 for(const selector of ['[data-open-camera]','[data-endpoint-images]','[data-depth-file]','[data-use-clinical]'])q(selector).disabled=!operatedSide;
 const context=()=>({patient_id:patientId,operation_date:operationDate,date:field('date').value,side:field('side').value,motion:field('motion').value,mode:field('mode').value,position:field('position').value});
 function updateButtons(){
  q('[data-capture]').disabled=!operatedSide||!cameraReady;
  q('[data-capture]').textContent=counting?'Cancel countdown':capturing?'Finish measurement now':'Capture this position';
  q('[data-open-camera]').disabled=!operatedSide||capturing||counting;
  q('[data-save-measurement]').disabled=!operatedSide||(!draft&&!completed.length)||capturing||counting;
  q('[data-save-measurement]').textContent=completed.length&&draft?'Save both measurements':completed.length?'Save bending only':'Save recovery measurement';
  q('[data-stop-camera]').disabled=!cameraReady&&!capturing&&!counting;
  field('date').readOnly=cameraReady||capturing||counting;
  field('motion').disabled=q('[data-measurement-plan]').value==='both'||capturing||counting;
  q('[data-measurement-plan]').disabled=capturing||counting;
 }
 function preview(result){draft=result;capturing=false;const entries=[...completed,...(result?[result]:[])];q('[data-measurement-preview]').hidden=!entries.length;
  q('[data-measurement-preview]').innerHTML=entries.map(item=>{const value=item.summary?.mean??item.value,motion=item.context?.motion||field('motion').value,date=item.context?.date||field('date').value;return `<div class="rs-result"><span class="eyebrow">${esc(SOURCE_NAMES[item.source.kind])} · ${esc(MOTION_NAMES[motion])}</span><strong>${degrees(value)}${motion==='straighten'?' of bend remaining':' of bend'}</strong><p>${esc(shortDate(date))} · ${esc(dayLabel(postOpDay(date,operationDate)))}</p><p>${item.summary?`Average of ${item.summary.accepted} usable pictures out of ${item.summary.sampled}. Readings ranged from ${degrees(item.summary.minimum)} to ${degrees(item.summary.maximum)}.`:'Clinical result entered for review.'}</p>${(item.summary?.warnings||[]).map(text=>`<p class="rs-quality-note">${esc(text)}</p>`).join('')}</div>`;}).join('')+(entries.length?'<p>These are approximate recorded angles. They do not prove your maximum possible range.</p>':'');
  updateButtons();
 }
 const voice=options.voiceFactory?options.voiceFactory():new AppVoice();
 const countdown=new EndpointCountdown({voice,onTick:n=>{counting=true;q('[data-countdown]').hidden=false;q('[data-countdown]').textContent=n;q('[data-sequence-status]').textContent=`${field('motion').value==='bend'?'Bending':'Straightening'} starts after the countdown. Use this time to settle comfortably; there is no need to hold your limit yet.`;updateButtons();},onStart:trigger=>{counting=false;q('[data-countdown]').hidden=true;camera.capture(trigger);updateButtons();},onCancel:()=>{counting=false;q('[data-countdown]').hidden=true;camera.resumeGesture?.();updateButtons();}});
 function prepareVoice(){const names=['countdown','recovery_bend','recovery_straighten','recovery_complete'];Promise.all(names.map(name=>voice.prepare(name))).then(ready=>{if(!alive)return;q('[data-voice-status]').textContent=ready.every(Boolean)?'Marin (AI voice) countdown and guidance are ready.':ready[0]?'Marin countdown is ready. Some spoken guidance is unavailable; follow the written instructions.':'Audio is unavailable. Follow the on-screen countdown and instructions.';});}
 function requestCountdown(trigger){if(!cameraReady||capturing||counting)return;liveAttempt=true;countdown.start(trigger);}
 function cameraResult(result){
  if(!result){preview(null);q('[data-sequence-status]').textContent='No measurement yet. Relax, then try again when ready.';return;}
  const item={...result,capture_group:captureGroup,context:context()};
  if(liveAttempt&&q('[data-measurement-plan]').value==='both'&&field('motion').value==='bend'){
   completed=[item];preview(null);field('motion').value='straighten';
   q('[data-sequence-status]').textContent='Bending captured. Relax and take your time. Next, straighten your operated knee as far as comfortable. Show your open palm when ready for the second countdown. You can also save bending only.';
   voice.play('recovery_straighten');updateButtons();
  }else{preview(item);if(liveAttempt){camera.stop();voice.play('recovery_complete');q('[data-sequence-status]').textContent='Capture finished. Relax your operated leg. Review and save your results below.';}}
 }
 function dateCaptureToday(){const date=localDate();field('date').max=date;field('date').value=date;summaryDate.max=date;}
 function captureStarted(){dateCaptureToday();captureGroup=crypto.randomUUID();field('confirmed').checked=true;draft=null;capturing=true;q('[data-measurement-preview]').hidden=true;updateButtons();}
 function gestureChanged({stage,progress=0}){
  if(counting)return;
  q('[data-gesture-guide]').hidden=stage==='off';q('[data-gesture-progress]').value=progress;
  const labels={ready:'At your limit? Show your open palm or use the red button.',holding:`Keep your palm open… ${Math.max(1,Math.ceil(2*(1-progress)))}`,capturing:`Picture ${Math.round(progress*10)} of 10. Small movements are fine; relax if needed.`,complete:'Capture finished. You can relax your leg.',release:'Lower or close your hand before another capture.',unavailable:'Hand detection unavailable. Use the red capture button below.'};
  q('[data-gesture-label]').textContent=labels[stage]||'';
  q('[data-gesture-progress]').hidden=!['holding','capturing'].includes(stage);
 }
 const camera=(options.cameraFactory||createEndpointCamera)({video:q('[data-endpoint-video]'),canvas:q('[data-endpoint-canvas]'),onStatus:s=>{q('[data-camera-status]').textContent=s;},onReady:ready=>{cameraReady=ready;if(ready)voice.play(field('motion').value==='bend'?'recovery_bend':'recovery_straighten');updateButtons();},onCaptureStart:captureStarted,onGesture:gestureChanged,onAngle:reading=>{q('[data-live-angle]').textContent=degrees(reading?.angle);},onTrigger:requestCountdown,onResult:cameraResult});
 function invalidate(){countdown.cancel();camera.stop();completed=[];liveAttempt=false;cameraReady=false;capturing=false;captureGroup='';field('confirmed').checked=false;preview(null);q('[data-camera-status]').textContent='Measurement setup changed. Open the camera or load a new result for this setup.';}
 for(const name of ['motion','side','mode','position','date'])field(name).onchange=invalidate;
 q('[data-open-camera]').onclick=()=>{if(!operatedSide)return;countdown.cancel();completed=[];if(q('[data-measurement-plan]').value==='both')field('motion').value='bend';preview(null);q('[data-save-status]').textContent='';q('[data-sequence-status]').textContent=field('motion').value==='bend'?'Bending first. Get comfortably positioned, then show your open palm for the countdown.':'Straightening. Get comfortably positioned, then show your open palm for the countdown.';prepareVoice();dateCaptureToday();field('confirmed').checked=false;q('.rs-camera-wrap').hidden=false;q('[data-camera-status]').textContent='Opening camera…';camera.start(operatedSide);q('[data-stop-camera]').disabled=false;};
 q('[data-capture]').onclick=()=>{if(counting){countdown.cancel();q('[data-sequence-status]').textContent='Countdown cancelled. Rest, then signal when ready.';}else if(capturing)camera.finish();else if(camera.requestCapture)camera.requestCapture();else requestCountdown('button');};
 q('[data-stop-camera]').onclick=()=>{countdown.cancel();camera.stop();cameraReady=false;capturing=false;updateButtons();q('[data-camera-status]').textContent='Camera stopped.';};
 q('[data-endpoint-images]').onchange=async e=>{const files=[...e.target.files];if(!q('[data-photo-view]').checked){q('[data-camera-status]').textContent='Confirm that the photographs use the same side-on camera view before analysing them.';e.target.value='';return;}invalidate();q('.rs-camera-wrap').hidden=true;await camera.images(files,field('side').value);e.target.value='';};
 q('[data-depth-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;invalidate();try{if(file.size>2*1024*1024)throw Error('Use a depth export smaller than 2 MB.');const imported=depthImport(JSON.parse(await file.text()),context());captureGroup=imported.capture_group;preview({...imported,context:context()});q('[data-camera-status]').textContent='Depth-camera import ready to review. No camera connection was made.';}catch(error){q('[data-camera-status]').textContent=`Could not import: ${error.message}`;}e.target.value='';};
 q('[data-use-clinical]').onclick=()=>{invalidate();const raw=field('clinical_angle').value,device=field('clinical_device').value.trim();if(raw===''||!Number.isFinite(Number(raw))||Number(raw)<0||Number(raw)>180||!device){q('[data-save-status]').textContent='Enter the clinical angle and the instrument or method used.';return;}preview({value:Number(raw),source:{kind:'clinical',device,method:'Unsigned knee bend entered from clinical assessment'},context:context()});};
 q('[data-measurement-plan]').onchange=()=>{invalidate();if(q('[data-measurement-plan]').value==='both')field('motion').value='bend';updateButtons();};
 const selectedTrends={bend:'',straighten:''};
 function drawPrimaryTrends(current){
  const trends={},groups={};
  for(const motion of ['bend','straighten']){
   const available=current.filter(r=>r.motion===motion);groups[motion]=new Map(available.map(r=>[measurementSeriesKey(r),r]));
   if(!groups[motion].has(selectedTrends[motion]))selectedTrends[motion]=available.length?measurementSeriesKey(available.at(-1)):'';
   trends[motion]=maximumMovementTrend(current,motion,selectedTrends[motion],operationDate);
  }
  const points=[...trends.bend.points,...trends.straighten.points].sort((a,b)=>a.day-b.day||a.motion.localeCompare(b.motion));
  q('[data-recovery-graphs]').innerHTML=`<section class="rs-primary-trend rs-combined-trend"><h2>Knee bending and straightening</h2>
   <div class="rs-combined-stats">${['bend','straighten'].map(motion=>{const best=trends[motion].best;return `<div class="rs-combined-stat" data-trend-stat="${motion}"><span class="rs-series-label"><i class="rs-series-marker ${motion}" aria-hidden="true"></i>${motion==='bend'?'Maximum knee bending':'Maximum knee straightening'}</span><div class="rs-trend-best"><strong>${best?degrees(best.value):'Not measured'}</strong><span>${motion==='bend'?'Best recorded comfortable bend':'Least bend remaining'}${best?`<small>Day ${best.day} · ${esc(shortDate(best.date))}</small>`:''}</span></div></div>`;}).join('')}</div>
   ${combinedMovementChart({bend:trends.bend.points,straighten:trends.straighten.points},postOpDay(summaryDate.value,operationDate))}
   <p class="rs-chart-note">The Y axis covers 0–150° of knee bend, with extra space for any larger recorded angle. 0° means a straight knee. This is a display range, not a recovery target. Bending shows the highest recorded average each day; straightening shows the lowest bend remaining. Missing days have no plotted value. Normal movement varies with age and the person; <a href="https://archive.cdc.gov/www_cdc_gov/ncbddd/jointrom/index.html" target="_blank" rel="noopener">CDC reference values</a> provide context, not a postoperative deadline. The faint band and the dashed line are published figures from other patients, shown for context and not as targets: the middle half of patients for bending (Kittelson 2020, 327 patients) and the mean bend remaining for straightening (Kornuijt 2019, 137 patients). Both were measured by clinicians rather than by a camera, and each stops where its paper stops.</p>
   ${operationDate?'':'<p><a href="./#opdate">Enter your operation date</a> to place measurements on the graph.</p>'}
   <details class="rs-chart-values"><summary>Measurement setup and graph values</summary><div class="rs-combined-setups">${['bend','straighten'].map(motion=>`<label class="rs-trend-setup">${motion==='bend'?'Bending':'Straightening'} measurement setup<select data-trend-motion="${motion}"${groups[motion].size?'':' disabled'}>${[...groups[motion]].map(([key,r])=>`<option value="${esc(key)}"${key===selectedTrends[motion]?' selected':''}>${esc(note(r))} · ${esc(r.source.device)}</option>`).join('')||'<option>No measurements yet</option>'}</select></label>`).join('')}</div><ul>${points.map(r=>`<li>${r.motion==='bend'?'Bending':'Straightening'} · Day ${r.day} · ${esc(shortDate(r.date))}: ${degrees(r.value)}${r.motion==='straighten'?' bend remaining':''}${r.summary?.warnings?.length?` · ${esc(r.summary.warnings.join(' '))}`:''}</li>`).join('')||'<li>No measured values yet.</li>'}</ul></details>
   <div class="rs-measure-choices"><button type="button" data-start-motion="bend">Measure bending →</button><button type="button" data-start-motion="straighten">Measure straightening →</button></div></section>`;
  q('[data-recovery-graphs]').querySelectorAll('[data-trend-motion]').forEach(select=>select.onchange=()=>{selectedTrends[select.dataset.trendMotion]=select.value;drawPrimaryTrends(chosenRows());q('.rs-chart-values').open=true;});
  q('[data-recovery-graphs]').querySelectorAll('[data-start-motion]').forEach(button=>button.onclick=()=>chooseMotion(button.dataset.startMotion));
 }
 function chooseMotion(motion){invalidate();q('[data-measurement-plan]').value='single';field('motion').value=motion;updateButtons();field('side').value=operatedSide||'';q('#recoveryCheck').scrollIntoView({block:'start'});field('motion').focus({preventScroll:true});}
 function chosenRows(){return scopedMeasurements(rows,patientId,operationDate,summarySide.value,summaryDate.value);}
 function draw(){
  if(dayNumber(summaryDate.value)===null||summaryDate.value>localDate()){q('.rs-storage-error').textContent='Choose a valid summary date no later than today.';return;}
  q('[data-summary-day]').textContent=dayLabel(postOpDay(summaryDate.value,operationDate));const current=chosenRows(),exercise=recoveryExerciseContext(exerciseRecords,{patientId,operationDate,side:summarySide.value,asOf:summaryDate.value});
  drawPrimaryTrends(current);
  const reported=proms.filter(r=>r.side===summarySide.value&&r.date<=summaryDate.value),latestScores=Object.keys(PROM_NAMES).map(id=>reported.filter(r=>r.instrument===id).at(-1)).filter(Boolean);
  q('[data-recovery-cards]').innerHTML=`<div class="rs-outcomes"><section class="rs-outcome"><div class="rs-outcome-label">Movement control</div><strong>${exercise.extraBend===null?'Not observed':`${degrees(exercise.extraBend)} extra bend`}</strong><p>${exercise.slr?`During the latest analysed straight leg raise, ${esc(shortDate(exercise.slr.started_at.slice(0,10)))}.`:'An analysed straight leg raise can show how the knee position changes during lifting.'}</p><small>Exercise observation. It does not measure physiological muscle activation.</small><a href="?view=progress-to-date">See exercise detail →</a></section><section class="rs-outcome"><div class="rs-outcome-label">Exercise participation</div><strong>${exercise.recent.length} saved sessions</strong><p>On ${exercise.days} of the last 7 calendar days, for this knee.</p><small>Describes recorded activity, not adherence to the whole prescribed programme or a strength score.</small><a href="?view=progress#progress">View exercise history →</a></section>${latestScores.length?`<section class="rs-outcome rs-reported"><div class="rs-outcome-label">How your knee feels and functions</div>${latestScores.map(r=>`<div><strong>${esc(PROM_NAMES[r.instrument])}: ${r.score}/${r.instrument==='koos_jr'?100:48}</strong><p>${esc(shortDate(r.date))} · Official questionnaire result entered separately.</p></div>`).join('')}<a href="?view=patient-measures">View questionnaire results →</a></section>`:''}</div><p class="rs-measure-note">0° means straight in this angle convention. Camera readings cannot establish hyperextension or clinical extension lag. A few degrees of change can reflect the setup or measurement variation.</p>`;
 }
 form.onsubmit=e=>{e.preventDefault();const entries=[...completed,...(draft?[draft]:[])];if(!entries.length)return;try{
  if(draft&&JSON.stringify(draft.context)!==JSON.stringify(context()))throw Error('The setup changed. Take or load a new measurement.');
  const saved=saveMeasurementSet(entries.map(item=>({...item.context,...item,confirmed:field('confirmed').checked,note:field('note').value})),{patientId,operationDate,storage});
  rows=readMeasurements(storage);for(const row of saved)selectedTrends[row.motion]=measurementSeriesKey(row);const last=saved.at(-1);summarySide.value=last.side;summaryDate.value=last.date;
  countdown.cancel();camera.stop();completed=[];cameraReady=false;capturing=false;preview(null);field('confirmed').checked=false;field('note').value='';draw();
  q('[data-save-status]').textContent=`Saved ${saved.length===2?'both measurements':MOTION_NAMES[last.motion].toLowerCase()} on ${shortDate(last.date)}. Stored on this device. ${[...new Set(saved.flatMap(row=>row.summary?.warnings||[]))].join(' ')}`;
 }catch(error){q('[data-save-status]').textContent=`Could not save: ${error.message}`;}};
 summarySide.onchange=draw;summaryDate.onchange=draw;
 q('[data-export-measurements]').onclick=()=>csvDownload('dedicated-recovery-measurements.csv',[['Patient','Operation date','Measurement date','Knee','Movement','Degrees of bend','Assistance','Position','Source','Device','Method','Calibration','Capture reference','Capture timestamp','Usable frames','Sampled frames','Capture notes','Patient reported limit','Note'],...scopedMeasurements(rows,patientId,operationDate).map(r=>[r.patient_id,r.operation_date,r.date,r.side,MOTION_NAMES[r.motion],r.value,MODE_NAMES[r.mode],POSITION_NAMES[r.position],SOURCE_NAMES[r.source.kind],r.source.device,r.source.method,r.source.calibration,r.capture_group,r.captured_at,r.summary?.accepted,r.summary?.sampled,(r.summary?.warnings||[]).join(' '),r.patient_confirmed_limit,r.note])]);
 q('[data-summary-download]').onclick=()=>download('patient-recovery-summary.txt',[`PATIENT RECOVERY SUMMARY`,`Patient: ${patientId}`,`Operation: ${operationDate||'Not set'}`,`As of: ${summaryDate.value} (${dayLabel(postOpDay(summaryDate.value,operationDate))})`,`Knee: ${summarySide.value}`,'',q('[data-recovery-graphs]').innerText,'',q('[data-recovery-cards]').innerText,'','Dedicated recovery checks are separate from exercise peaks. Camera estimates are not clinically validated.',`Typical recovery timeline: ${RECOVERY_SOURCES.chart.url}`].join('\n'));
 const leave=()=>{countdown.cancel();camera.stop();};window.addEventListener('pagehide',leave);host._destroy=()=>{alive=false;leave();voice.context?.close();window.removeEventListener('pagehide',leave);};updateButtons();draw();
}
