import {esc,shortDate,dayLabel,tile,chart,csvDownload,download} from './progress-shared.mjs';
import {localDate,postOpDay,dayNumber,dayAt,finite,METRICS} from './progress-data.mjs';
import {readProms,scopedProms,PROM_NAMES} from './patient-measures.mjs';
import {readMeasurements,scopedMeasurements,saveMeasurement,endpointOverview,measurementSeriesKey,depthImport,compareSources,SOURCE_NAMES,MOTION_NAMES,MODE_NAMES,POSITION_NAMES,MEASUREMENT_VERSION} from './recovery-measurements.mjs';
import {createEndpointCamera} from './recovery-camera.mjs';
import {RECOVERY_SOURCES} from './recovery-references.mjs';

const degrees=n=>finite(n)===null?'Not measured':`${Math.round(n)}°`;
const note=r=>`${SOURCE_NAMES[r.source.kind]} · ${MODE_NAMES[r.mode]} · ${POSITION_NAMES[r.position]}`;
const metricValue=(r,id)=>finite(METRICS[r?.exercise]?.find(m=>m.id===id)?.get(r));
const src=(key,label)=>`<a href="${RECOVERY_SOURCES[key].url}" target="_blank" rel="noopener">${label}</a>`;
export function recoveryExerciseContext(records,{patientId,operationDate,side,asOf=localDate()}){
 const scoped=records.filter(r=>r.patient_id===patientId&&(r.operation_date||'')===(operationDate||'')&&dayNumber(r.started_at?.slice(0,10))!==null&&r.started_at.slice(0,10)<=asOf&&
  (r.exercise_analysis?.config?.side||r.measurement?.side)===side).sort((a,b)=>a.started_at.localeCompare(b.started_at));
 const recent=scoped.filter(r=>r.started_at.slice(0,10)>=dayAt(dayNumber(asOf)-6)),slr=scoped.filter(r=>r.exercise==='straight_leg_raise'&&metricValue(r,'extraBend')!==null).at(-1);
 const symptoms=scoped.filter(r=>finite(r.patient?.pain_0_10)!==null).at(-1);
 return {recent,days:new Set(recent.map(r=>r.started_at.slice(0,10))).size,slr,extraBend:slr?metricValue(slr,'extraBend'):null,symptoms};
}

export function renderRecoverySummary(host,exerciseRecords,options={}){
 host._destroy?.();
 const {patientId='',operationDate='',side:initialSide='left'}=options,storage=options.storage||localStorage;
 const today=localDate();let rows=[],proms=[],storageError='',draft=null,captureGroup='',preparedGroup='',cameraReady=false,capturing=false;
 try{rows=readMeasurements(storage);}catch(e){storageError=e.message;}
 try{proms=scopedProms(readProms(storage),patientId,operationDate);}catch(e){storageError+=[storageError?' ':'',e.message].join('');}
 host.innerHTML=`<header class="rs-heading"><div class="eyebrow">Your recovery · beyond exercise counts</div><h1>Recovery summary</h1><p>How your knee is moving, how it feels and what you can do. Dedicated movement checks are recorded separately from your exercises.</p><p class="pt-context">Patient ${esc(patientId)} · ${operationDate?`Operation ${esc(shortDate(operationDate))}`:'Operation date not set'} · <a href="?view=settings#patient">Change patient details</a></p></header>
 <div class="rs-summary-controls"><label>Knee in summary<select data-summary-side><option value="left">Left knee</option><option value="right">Right knee</option></select></label><label>Summary date<input data-summary-date type="date" value="${today}" max="${today}"></label><span data-summary-day></span></div>
 <p class="rs-storage-error" role="status">${esc(storageError)}</p><div data-recovery-cards></div>
 <section class="rs-panel rs-measure" id="recoveryCheck"><div class="eyebrow">A separate recovery check</div><h2>Measure your bend or straightening</h2><p>Use the position and assistance agreed with your physiotherapist. Move to your comfortable limit and tell the app when you are there. There is no required pause at the start.</p>
 <form data-endpoint-form><div class="rs-fields"><label>Movement<select name="motion"><option value="bend">Knee bending</option><option value="straighten">Knee straightening</option></select></label><label>Knee being measured<select name="side"><option value="left">Left knee</option><option value="right">Right knee</option></select></label><label>Assistance<select name="mode"><option value="active">Without assistance</option><option value="assisted">With assistance</option><option value="passive">Clinician-assessed passive range</option></select></label><label>Position<select name="position"><option value="supine">Lying on your back</option><option value="seated">Seated</option></select></label><label>Measurement date<input name="date" type="date" required value="${today}" max="${today}"></label></div>
 <div class="rs-camera-guide"><span class="rs-step">1</span><p>Place the camera side-on, with the hip, knee and ankle visible. Keep the same setup for later comparisons.</p><span class="rs-step">2</span><p>At your comfortable limit, press capture or ask a helper to press it. A short sequence is averaged while you hold this position.</p><span class="rs-step">3</span><p>Relax your leg, review the result and save it. These camera estimates have not been clinically validated.</p></div>
 <div class="rs-camera-wrap" hidden><video data-endpoint-video muted playsinline hidden></video><canvas data-endpoint-canvas aria-label="Camera view with the measured leg highlighted"></canvas></div><div class="rs-camera-actions"><button type="button" class="pt-primary" data-open-camera>Open camera</button><button type="button" class="pt-primary" data-capture disabled>I’m at my comfortable limit · capture</button><button type="button" data-stop-camera disabled>Stop camera</button></div><p data-camera-status role="status">The camera starts only when you open it. No microphone is used.</p>
 <details class="rs-alternative"><summary>Use a sequence of photos instead</summary><p>Select 6 to 60 photos of the same knee at the same reported end position. Use the same setup and select the date they were taken. Do not mix different attempts or positions.</p><label class="rs-upload">End-position photos<input data-endpoint-images type="file" accept="image/*" multiple></label></details>
 <details class="rs-alternative"><summary>Add a 3D camera or clinical measurement</summary><p><strong>3D camera: not connected.</strong> A compatible device export can be imported below. Direct capture will need the camera model and its software connection.</p><label class="rs-upload">Import depth-camera joint coordinates (JSON)<input data-depth-file type="file" accept=".json,application/json"></label><p>The importer calculates the bend from depth-derived hip, knee and ankle coordinates. MediaPipe’s predicted 3D landmarks are not a second camera measurement.</p><details><summary>Depth-camera comparison setup</summary><p>To compare cameras, collect the same knee, position and assistance during the same patient-reported hold. Both exports need the same capture reference and aligned timestamps. Download a request for the device integration; it contains no example patient measurements.</p><button type="button" data-depth-request>Download depth capture reference</button><p data-capture-reference></p></details><div class="rs-fields"><label>Clinical angle, degrees of bend<input name="clinical_angle" type="number" min="0" max="180" step="0.1" placeholder="0 means straight"></label><label>Clinical instrument or method<input name="clinical_device" maxlength="160" placeholder="For example, goniometer"></label></div><button type="button" data-use-clinical>Use this clinical result</button><p>Enter a result already measured by a clinician. This unsigned angle format cannot record hyperextension or calculate clinical extension lag.</p></details>
 <section data-measurement-preview class="rs-preview" aria-live="polite" hidden></section><label class="pt-check"><input name="confirmed" type="checkbox"><span>The patient reported reaching their comfortable limit for this measurement.</span></label><label class="rs-note">Note, including any assistance or symptoms<textarea name="note" rows="2" maxlength="1000"></textarea></label><button type="submit" class="pt-primary" data-save-measurement disabled>Save recovery measurement</button><p data-save-status role="status"></p></form></section>
 <section class="rs-panel"><h2>Recovery measurements over time</h2><p>These are dedicated end-position checks. Exercise peaks stay in <a href="?view=progress-to-date">Exercise metrics</a>. Compare the same source, knee, assistance and position.</p><div class="rs-fields"><label>Measurement series<select data-measurement-series></select></label></div><div data-measurement-history></div><button type="button" data-export-measurements>Download recovery measurements (CSV)</button></section>
 <details class="rs-panel rs-comparison"><summary>Compare the two camera sources</summary><p>Select results from the same hold. The readings, their difference and their equal-weight average remain visible. The combined average is experimental and is not used as the main recovery result.</p><div class="rs-fields"><label>MediaPipe reading<select data-compare-a></select></label><label>Depth-camera reading<select data-compare-b></select></label></div><label class="pt-check"><input data-pair-confirmed type="checkbox"><span>These are two camera observations of the same patient-reported hold.</span></label><div data-comparison role="status"></div><p class="pt-muted">Agreement does not establish accuracy. A depth-derived angle and a side-view projected angle can differ because of the measurement method. Validation needs an appropriate independent reference. The timing and frame rules here are prototype checks, not clinical thresholds.</p></details>
 <footer class="rs-footer"><p>Typical recovery involves movement, symptoms, strength and everyday function. These do not all improve at the same rate. ${src('function','Mizner et al.')}</p><div class="pt-actions"><a class="pt-link-button" href="?view=recovery-timeline">Expected recovery timeline →</a><a class="pt-link-button" href="?view=progress-to-date">Exercise metrics →</a><button type="button" data-summary-download>Download patient summary</button></div></footer>`;
 const q=s=>host.querySelector(s),form=q('[data-endpoint-form]'),field=n=>form.elements.namedItem(n),summarySide=q('[data-summary-side]'),summaryDate=q('[data-summary-date]'),series=q('[data-measurement-series]');
 summarySide.value=['left','right'].includes(initialSide)?initialSide:'left';field('side').value=summarySide.value;
 const context=()=>({patient_id:patientId,operation_date:operationDate,date:field('date').value,side:field('side').value,motion:field('motion').value,mode:field('mode').value,position:field('position').value});
 function updateButtons(){q('[data-capture]').disabled=!cameraReady||capturing;q('[data-open-camera]').disabled=capturing;q('[data-save-measurement]').disabled=!draft||capturing;q('[data-stop-camera]').disabled=!cameraReady&&!capturing;}
 function preview(result){draft=result;capturing=false;q('[data-measurement-preview]').hidden=!result;
  if(result){const value=result.summary?.mean??result.value;q('[data-measurement-preview]').innerHTML=`<span class="eyebrow">${esc(SOURCE_NAMES[result.source.kind])} · ${esc(MOTION_NAMES[field('motion').value])}</span><strong>${degrees(value)}${field('motion').value==='straighten'?' of bend remaining':' of bend'}</strong><p>${result.summary?`Average of ${result.summary.accepted} usable frames out of ${result.summary.sampled}. Readings ranged from ${degrees(result.summary.minimum)} to ${degrees(result.summary.maximum)}.`:'Clinical result entered for review.'}</p><p>The patient identifies their limit. This does not prove their maximum possible range or a change in strength.</p>`;}
  updateButtons();
 }
 const camera=(options.cameraFactory||createEndpointCamera)({video:q('[data-endpoint-video]'),canvas:q('[data-endpoint-canvas]'),onStatus:s=>{q('[data-camera-status]').textContent=s;},onReady:ready=>{cameraReady=ready;updateButtons();},onResult:result=>preview(result?{...result,capture_group:captureGroup,context:context()}:null)});
 function invalidate(){camera.stop();cameraReady=false;capturing=false;captureGroup='';preparedGroup='';field('confirmed').checked=false;preview(null);q('[data-camera-status]').textContent='Measurement setup changed. Open the camera or load a new result for this setup.';}
 for(const name of ['motion','side','mode','position','date'])field(name).onchange=invalidate;
 q('[data-open-camera]').onclick=()=>{preview(null);field('date').value=localDate();field('confirmed').checked=false;q('.rs-camera-wrap').hidden=false;q('[data-camera-status]').textContent='Opening camera…';camera.start(field('side').value);q('[data-stop-camera]').disabled=false;};
 q('[data-capture]').onclick=()=>{captureGroup=preparedGroup||crypto.randomUUID();preparedGroup='';field('confirmed').checked=true;draft=null;q('[data-measurement-preview]').hidden=true;capturing=camera.capture();updateButtons();q('[data-capture-reference]').textContent=`Capture reference: ${captureGroup}`;};
 q('[data-stop-camera]').onclick=()=>{camera.stop();cameraReady=false;capturing=false;updateButtons();q('[data-camera-status]').textContent='Camera stopped.';};
 q('[data-endpoint-images]').onchange=async e=>{const files=[...e.target.files];invalidate();q('.rs-camera-wrap').hidden=true;await camera.images(files,field('side').value);e.target.value='';};
 q('[data-depth-file]').onchange=async e=>{const file=e.target.files[0];if(!file)return;invalidate();try{if(file.size>2*1024*1024)throw Error('Use a depth export smaller than 2 MB.');const imported=depthImport(JSON.parse(await file.text()),context());captureGroup=imported.capture_group;preview({...imported,context:context()});q('[data-camera-status]').textContent='Depth-camera import ready to review. No camera connection was made.';}catch(error){q('[data-camera-status]').textContent=`Could not import: ${error.message}`;}e.target.value='';};
 q('[data-use-clinical]').onclick=()=>{invalidate();const raw=field('clinical_angle').value,device=field('clinical_device').value.trim();if(raw===''||!Number.isFinite(Number(raw))||Number(raw)<0||Number(raw)>180||!device){q('[data-save-status]').textContent='Enter the clinical angle and the instrument or method used.';return;}preview({value:Number(raw),source:{kind:'clinical',device,method:'Unsigned knee bend entered from clinical assessment'},context:context()});};
 q('[data-depth-request]').onclick=()=>{if(!draft)preparedGroup=preparedGroup||crypto.randomUUID();captureGroup=draft?.capture_group||preparedGroup;q('[data-capture-reference]').textContent=`Capture reference: ${captureGroup}`;download('depth-capture-request.json',JSON.stringify({schema:'knee-depth-endpoint-v1',...context(),capture_group:captureGroup,captured_at:draft?.captured_at||null,units:'m',source:{kind:'depth_3d',coordinates:'depth-derived-joint-centres',device:'',calibration:''},frames:[]},null,2),'application/json');};
 function rangeCard(motion,current){
  const {latest,previous,change}=endpointOverview(current,motion);return `<section class="rs-outcome rs-range"><div class="rs-outcome-label">${esc(MOTION_NAMES[motion])}</div><strong>${latest?degrees(latest.value):'Not measured'}</strong><p>${motion==='bend'?'Bend at your reported comfortable limit':'Bend remaining at your reported straightest position'}</p><small>${latest?`${esc(shortDate(latest.date))} · ${esc(note(latest))}`:'Take a dedicated movement check below.'}</small>${previous?`<p class="rs-change">${change>=0?'+':''}${Math.round(change)}° from ${esc(shortDate(previous.date))}, using the same measurement setup.</p>`:''}<button type="button" data-start-motion="${motion}">Measure ${motion==='bend'?'bending':'straightening'} →</button></section>`;
 }
 function chosenRows(){return scopedMeasurements(rows,patientId,operationDate,summarySide.value,summaryDate.value);}
 function drawHistory(){
  const chosen=chosenRows().filter(r=>measurementSeriesKey(r)===series.value),daily=new Map();for(const r of chosen)daily.set(r.date,{date:r.date,value:r.value});
  q('[data-measurement-history]').innerHTML=`${chart([...daily.values()],'°','Dedicated knee movement checks')}<div class="pt-table-wrap"><table><caption>Dedicated recovery checks for the selected series</caption><thead><tr><th>Date</th><th>After surgery</th><th>Result</th><th>How measured</th><th>Note</th></tr></thead><tbody>${chosen.slice().reverse().map(r=>`<tr><th scope="row">${esc(shortDate(r.date))}</th><td>${esc(dayLabel(postOpDay(r.date,operationDate)))}</td><td>${degrees(r.value)}${r.motion==='straighten'?' bend remaining':''}</td><td>${esc(note(r))}<small>${esc(r.source.device)}${r.summary?` · ${r.summary.accepted}/${r.summary.sampled} usable frames`:''}</small></td><td>${esc(r.note)}</td></tr>`).join('')||'<tr><td colspan="5">No dedicated recovery measurements in this series.</td></tr>'}</tbody></table></div>`;
 }
 function drawComparison(){const current=chosenRows(),a=current.find(r=>r.id===q('[data-compare-a]').value),b=current.find(r=>r.id===q('[data-compare-b]').value),comparison=compareSources(a,b,q('[data-pair-confirmed]').checked);q('[data-comparison]').innerHTML=comparison.available?`<div class="pt-tiles">${tile('MediaPipe',degrees(a.value),'2D projected knee bend')}${tile('Depth camera',degrees(b.value),'3D joint-centre knee bend')}${tile('Difference',degrees(comparison.difference),'No validated agreement threshold applied')}${tile('Experimental average',degrees(comparison.mean),'Equal weight; excluded from recovery trends')}</div><p>${esc(comparison.reason)}</p>`:`<p>${esc(comparison.reason)}</p>`;}
 function draw(){
  if(dayNumber(summaryDate.value)===null||summaryDate.value>localDate()){q('.rs-storage-error').textContent='Choose a valid summary date no later than today.';return;}
  q('[data-summary-day]').textContent=dayLabel(postOpDay(summaryDate.value,operationDate));const current=chosenRows(),exercise=recoveryExerciseContext(exerciseRecords,{patientId,operationDate,side:summarySide.value,asOf:summaryDate.value});
  const reported=proms.filter(r=>r.side===summarySide.value&&r.date<=summaryDate.value),latestScores=Object.keys(PROM_NAMES).map(id=>reported.filter(r=>r.instrument===id).at(-1)).filter(Boolean);
  q('[data-recovery-cards]').innerHTML=`<div class="rs-outcomes">${rangeCard('bend',current)}${rangeCard('straighten',current)}<section class="rs-outcome"><div class="rs-outcome-label">Movement control</div><strong>${exercise.extraBend===null?'Not observed':`${degrees(exercise.extraBend)} extra bend`}</strong><p>${exercise.slr?`During the latest analysed straight leg raise, ${esc(shortDate(exercise.slr.started_at.slice(0,10)))}.`:'An analysed straight leg raise can show how the knee position changes during lifting.'}</p><small>Exercise observation. It does not measure physiological muscle activation.</small><a href="?view=progress-to-date">See exercise detail →</a></section><section class="rs-outcome"><div class="rs-outcome-label">Muscle strength</div><strong>Not measured</strong><p>Strength needs an appropriate force or torque assessment, such as dynamometry.</p><small>Repetitions, lift height and participation cannot establish a strength value. ${src('strength','Strength recovery evidence')}</small></section><section class="rs-outcome"><div class="rs-outcome-label">Exercise participation</div><strong>${exercise.recent.length} saved sessions</strong><p>On ${exercise.days} of the last 7 calendar days, for this knee.</p><small>Describes recorded activity, not adherence to the whole prescribed programme or a strength score.</small><a href="?view=progress#progress">View exercise history →</a></section><section class="rs-outcome"><div class="rs-outcome-label">Pain and effort</div><strong>${exercise.symptoms?`${exercise.symptoms.patient.pain_0_10}/10 pain`:'Not reported'}</strong><p>${exercise.symptoms?`After exercise on ${esc(shortDate(exercise.symptoms.started_at.slice(0,10)))}.${finite(exercise.symptoms.patient.difficulty_1_5)!==null?` Effort: ${exercise.symptoms.patient.difficulty_1_5}/5.`:''}`:'Pain and effort appear when entered after an exercise.'}</p><small>Post-exercise symptoms, not a resting pain or swelling assessment.</small></section>${latestScores.length?`<section class="rs-outcome rs-reported"><div class="rs-outcome-label">How your knee feels and functions</div>${latestScores.map(r=>`<div><strong>${esc(PROM_NAMES[r.instrument])}: ${r.score}/${r.instrument==='koos_jr'?100:48}</strong><p>${esc(shortDate(r.date))} · Official questionnaire result entered separately.</p></div>`).join('')}<a href="?view=patient-measures">View questionnaire results →</a></section>`:''}</div><p class="rs-measure-note">0° means straight in this angle convention. Camera readings cannot establish hyperextension or clinical extension lag. A few degrees of change can reflect the setup or measurement variation.</p>`;
  q('[data-recovery-cards]').querySelectorAll('[data-start-motion]').forEach(button=>button.onclick=()=>{invalidate();field('motion').value=button.dataset.startMotion;field('side').value=summarySide.value;q('#recoveryCheck').scrollIntoView({block:'start'});field('motion').focus({preventScroll:true});});
  const prior=series.value,groups=new Map(current.map(r=>[measurementSeriesKey(r),r]));series.innerHTML=[...groups].map(([key,r])=>`<option value="${esc(key)}">${esc(MOTION_NAMES[r.motion])} · ${esc(note(r))} · ${esc(r.source.device)}</option>`).join('')||'<option value="">No measurements yet</option>';if(groups.has(prior))series.value=prior;drawHistory();
  for(const [selector,kind] of [['[data-compare-a]','mediapipe_2d'],['[data-compare-b]','depth_3d']])q(selector).innerHTML='<option value="">Select a result</option>'+current.filter(r=>r.source.kind===kind).map(r=>`<option value="${esc(r.id)}">${esc(shortDate(r.date))} · ${esc(MOTION_NAMES[r.motion])} · ${degrees(r.value)} · ${esc(r.capture_group.slice(0,8)||'No paired reference')}</option>`).join('');q('[data-pair-confirmed]').checked=false;drawComparison();
 }
 form.onsubmit=e=>{e.preventDefault();if(!draft)return;try{
  if(JSON.stringify(draft.context)!==JSON.stringify(context()))throw Error('The setup changed. Take or load a new measurement.');
  const saved=saveMeasurement({...context(),...draft,confirmed:field('confirmed').checked,note:field('note').value},{patientId,operationDate,storage});rows=readMeasurements(storage);summarySide.value=saved.side;summaryDate.value=saved.date;camera.stop();cameraReady=false;capturing=false;preview(null);field('confirmed').checked=false;field('note').value='';draw();q('[data-save-status]').textContent=`Saved ${MOTION_NAMES[saved.motion].toLowerCase()}: ${degrees(saved.value)} on ${shortDate(saved.date)}. Stored on this device.`;
 }catch(error){q('[data-save-status]').textContent=`Could not save: ${error.message}`;}};
 summarySide.onchange=draw;summaryDate.onchange=draw;series.onchange=drawHistory;for(const s of ['[data-compare-a]','[data-compare-b]','[data-pair-confirmed]'])q(s).onchange=drawComparison;
 q('[data-export-measurements]').onclick=()=>csvDownload('dedicated-recovery-measurements.csv',[['Patient','Operation date','Measurement date','Knee','Movement','Degrees of bend','Assistance','Position','Source','Device','Method','Calibration','Capture reference','Capture timestamp','Usable frames','Sampled frames','Patient reported limit','Note'],...scopedMeasurements(rows,patientId,operationDate).map(r=>[r.patient_id,r.operation_date,r.date,r.side,MOTION_NAMES[r.motion],r.value,MODE_NAMES[r.mode],POSITION_NAMES[r.position],SOURCE_NAMES[r.source.kind],r.source.device,r.source.method,r.source.calibration,r.capture_group,r.captured_at,r.summary?.accepted,r.summary?.sampled,r.patient_confirmed_limit,r.note])]);
 q('[data-summary-download]').onclick=()=>download('patient-recovery-summary.txt',[`PATIENT RECOVERY SUMMARY`,`Patient: ${patientId}`,`Operation: ${operationDate||'Not set'}`,`As of: ${summaryDate.value} (${dayLabel(postOpDay(summaryDate.value,operationDate))})`,`Knee: ${summarySide.value}`,'',q('[data-recovery-cards]').innerText,'','Dedicated recovery checks are separate from exercise peaks. Camera estimates are not clinically validated. Combined camera averages are experimental and excluded from this summary.',`Typical recovery timeline: ${RECOVERY_SOURCES.chart.url}`].join('\n'));
 const leave=()=>camera.stop();window.addEventListener('pagehide',leave);host._destroy=()=>{camera.stop();window.removeEventListener('pagehide',leave);};draw();
}
